name: CI
on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '10'
      - run: yarn install
      - run: yarn build_dev
      - uses: actions/upload-artifact@v2
        with:
          name: build-artifact
          path: build/
